services:
  word-radar:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: word-radar-server
    ports:
      - "8787:8787"
    volumes:
      - /Users/lei/dev/db/word-radar:/app/data
      - /Users/lei/dev/obsidian:/obsidian
      - ./server/confg.yaml:/app/confg.yaml # 配置挂载
    command: [ "--config", "/app/confg.yaml" ]
    # 环境变量仍可覆盖 confg.yaml 中的值（优先级更高）
    # environment:
    #   - LLM_API_KEY=sk-xxx
    restart: unless-stopped
